import { type Monaco } from "@monaco-editor/react";
import type { editor } from "monaco-editor";
import { langId } from "./language";

export const registerCompletionProvider = (monaco: Monaco) => {
  monaco.languages.registerCompletionItemProvider(langId, {
    provideCompletionItems: (
      model: editor.ITextModel,
      position: editor.Position
    ) => {
      const word = model.getWordUntilPosition(position);
      const range = {
        startLineNumber: position.lineNumber,
        endLineNumber: position.lineNumber,
        startColumn: word.startColumn,
        endColumn: word.endColumn,
      };

      const suggestions: monaco.languages.CompletionItem[] = [
        {
          label: "if",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "{% if ${1:condition} %}\n\t$0\n{% endif %}",
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja if statement",
          range,
        },
        {
          label: "ifelse",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText:
            "{% if ${1:condition} %}\n\t$2\n{% else %}\n\t$0\n{% endif %}",
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja if-else statement",
          range,
        },
        {
          label: "for",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "{% for ${1:item} in ${2:sequence} %}\n\t$0\n{% endfor %}",
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja for loop",
          range,
        },
        {
          label: "block",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "{% block ${1:name} %}\n\t$0\n{% endblock %}",
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja block",
          range,
        },
        {
          label: "extends",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: '{% extends "${1:template}" %}',
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja extends",
          range,
        },
        {
          label: "include",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: '{% include "${1:template}" %}',
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja include",
          range,
        },
        {
          label: "macro",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "{% macro ${1:name}(${2:args}) %}\n\t$0\n{% endmacro %}",
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja macro",
          range,
        },
        {
          label: "call",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "{% call ${1:name}(${2:args}) %}\n\t$0\n{% endcall %}",
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja call",
          range,
        },
        {
          label: "filter",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "{% filter ${1:name} %}\n\t$0\n{% endfilter %}",
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja filter block",
          range,
        },
        {
          label: "set",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "{% set ${1:name} = ${2:value} %}",
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja set variable",
          range,
        },
        {
          label: "raw",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "{% raw %}\n\t$0\n{% endraw %}",
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja raw block",
          range,
        },
        {
          label: "import",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: '{% import "${1:template}" as ${2:alias} %}',
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja import",
          range,
        },
        {
          label: "from",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: '{% from "${1:template}" import ${2:name} %}',
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          documentation: "Jinja from import",
          range,
        },
        { label: "abs", kind: monaco.languages.CompletionItemKind.Function, insertText: "abs", range },
        { label: "attr", kind: monaco.languages.CompletionItemKind.Function, insertText: "attr", range },
        { label: "batch", kind: monaco.languages.CompletionItemKind.Function, insertText: "batch", range },
        { label: "capitalize", kind: monaco.languages.CompletionItemKind.Function, insertText: "capitalize", range },
        { label: "center", kind: monaco.languages.CompletionItemKind.Function, insertText: "center", range },
        { label: "default", kind: monaco.languages.CompletionItemKind.Function, insertText: "default", range },
        { label: "dictsort", kind: monaco.languages.CompletionItemKind.Function, insertText: "dictsort", range },
        { label: "escape", kind: monaco.languages.CompletionItemKind.Function, insertText: "escape", range },
        { label: "filesizeformat", kind: monaco.languages.CompletionItemKind.Function, insertText: "filesizeformat", range },
        { label: "first", kind: monaco.languages.CompletionItemKind.Function, insertText: "first", range },
        { label: "float", kind: monaco.languages.CompletionItemKind.Function, insertText: "float", range },
        { label: "forceescape", kind: monaco.languages.CompletionItemKind.Function, insertText: "forceescape", range },
        { label: "format", kind: monaco.languages.CompletionItemKind.Function, insertText: "format", range },
        { label: "groupby", kind: monaco.languages.CompletionItemKind.Function, insertText: "groupby", range },
        { label: "indent", kind: monaco.languages.CompletionItemKind.Function, insertText: "indent", range },
        { label: "int", kind: monaco.languages.CompletionItemKind.Function, insertText: "int", range },
        { label: "join", kind: monaco.languages.CompletionItemKind.Function, insertText: "join", range },
        { label: "last", kind: monaco.languages.CompletionItemKind.Function, insertText: "last", range },
        { label: "length", kind: monaco.languages.CompletionItemKind.Function, insertText: "length", range },
        { label: "list", kind: monaco.languages.CompletionItemKind.Function, insertText: "list", range },
        { label: "lower", kind: monaco.languages.CompletionItemKind.Function, insertText: "lower", range },
        { label: "map", kind: monaco.languages.CompletionItemKind.Function, insertText: "map", range },
        { label: "max", kind: monaco.languages.CompletionItemKind.Function, insertText: "max", range },
        { label: "min", kind: monaco.languages.CompletionItemKind.Function, insertText: "min", range },
        { label: "pprint", kind: monaco.languages.CompletionItemKind.Function, insertText: "pprint", range },
        { label: "random", kind: monaco.languages.CompletionItemKind.Function, insertText: "random", range },
        { label: "reject", kind: monaco.languages.CompletionItemKind.Function, insertText: "reject", range },
        { label: "rejectattr", kind: monaco.languages.CompletionItemKind.Function, insertText: "rejectattr", range },
        { label: "replace", kind: monaco.languages.CompletionItemKind.Function, insertText: "replace", range },
        { label: "reverse", kind: monaco.languages.CompletionItemKind.Function, insertText: "reverse", range },
        { label: "round", kind: monaco.languages.CompletionItemKind.Function, insertText: "round", range },
        { label: "safe", kind: monaco.languages.CompletionItemKind.Function, insertText: "safe", range },
        { label: "select", kind: monaco.languages.CompletionItemKind.Function, insertText: "select", range },
        { label: "selectattr", kind: monaco.languages.CompletionItemKind.Function, insertText: "selectattr", range },
        { label: "slice", kind: monaco.languages.CompletionItemKind.Function, insertText: "slice", range },
        { label: "sort", kind: monaco.languages.CompletionItemKind.Function, insertText: "sort", range },
        { label: "string", kind: monaco.languages.CompletionItemKind.Function, insertText: "string", range },
        { label: "striptags", kind: monaco.languages.CompletionItemKind.Function, insertText: "striptags", range },
        { label: "sum", kind: monaco.languages.CompletionItemKind.Function, insertText: "sum", range },
        { label: "title", kind: monaco.languages.CompletionItemKind.Function, insertText: "title", range },
        { label: "tojson", kind: monaco.languages.CompletionItemKind.Function, insertText: "tojson", range },
        { label: "trim", kind: monaco.languages.CompletionItemKind.Function, insertText: "trim", range },
        { label: "truncate", kind: monaco.languages.CompletionItemKind.Function, insertText: "truncate", range },
        { label: "unique", kind: monaco.languages.CompletionItemKind.Function, insertText: "unique", range },
        { label: "upper", kind: monaco.languages.CompletionItemKind.Function, insertText: "upper", range },
        { label: "urlencode", kind: monaco.languages.CompletionItemKind.Function, insertText: "urlencode", range },
        { label: "urlize", kind: monaco.languages.CompletionItemKind.Function, insertText: "urlize", range },
        { label: "wordcount", kind: monaco.languages.CompletionItemKind.Function, insertText: "wordcount", range },
        { label: "wordwrap", kind: monaco.languages.CompletionItemKind.Function, insertText: "wordwrap", range },
        { label: "xmlattr", kind: monaco.languages.CompletionItemKind.Function, insertText: "xmlattr", range },
      ];

      return { suggestions };
    },
  });
};
