import type { Metadata } from "next";
import "./globals.css";
import {DM_Sans} from "next/font/google"
import { ThemeProvider } from "@/providers/theme-provider";
import { SidebarProviderWrapper } from "@/components/sidebar-provider";
import { PageTitleProvider } from "@/contexts/page-title-context";
import { AlertProvider } from "@/contexts/alert-context";
import { Toaster } from "sonner";
import { StoreInitializer } from "@/components/store-initializer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = DM_Sans({subsets:['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={font.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <StoreInitializer>
              <AlertProvider>
                <PageTitleProvider>
                  <SidebarProviderWrapper>
                    {children}
                    <Toaster 
                      position="top-right"
                      expand={true}
                      richColors={true}
                      closeButton={true}
                    />
                  </SidebarProviderWrapper>
                </PageTitleProvider>
              </AlertProvider>
            </StoreInitializer>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
